set "SERVERNAME=actualservernamegoeshere"
		
bcp A_Action in BCP\A_Action.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp A_ActionOption in BCP\A_ActionOption.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp A_BitCondition in BCP\A_BitCondition.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp A_Collection in BCP\A_Collection.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp A_CollectionAgent in BCP\A_CollectionAgent.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp A_CollectionClass in BCP\A_CollectionClass.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp A_DashBoard in BCP\A_DashBoard.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp A_DashBoardItem in BCP\A_DashBoardItem.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp A_FieldPattern in BCP\A_FieldPattern.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp A_File in BCP\A_File.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp A_FileAccess in BCP\A_FileAccess.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp A_FileUpload in BCP\A_FileUpload.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp A_SlotStatusDefinition in BCP\A_SlotStatusDefinition.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp A_Snippet in BCP\A_Snippet.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp AppGroup in BCP\AppGroup.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp AutoNotification in BCP\AutoNotification.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp Button in BCP\Button.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp Chart in BCP\Chart.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp DashboardFilter in BCP\DashboardFilter.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp DashboardFrame in BCP\DashboardFrame.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp DashboardGroup in BCP\DashboardGroup.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp DashboardSection in BCP\DashboardSection.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp DashboardText in BCP\DashboardText.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp DashboardWidget in BCP\DashboardWidget.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp Licence in BCP\Licence.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp Notices in BCP\Notices.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp NotificationTemplate in BCP\NotificationTemplate.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp NotificationTemplateButton in BCP\NotificationTemplateButton.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp Page in BCP\Page.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp ScheduleTimeTemplate in BCP\ScheduleTimeTemplate.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp Venn in BCP\Venn.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp VennRing in BCP\VennRing.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp Views in BCP\Views.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp A_FrameSite in BCP\A_FrameSite.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp BookType in BCP\BookType.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp A_AppCriteria in BCP\A_AppCriteria.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp Sys_Event in BCP\Sys_Event.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp Sys_Agent in BCP\Sys_Agent.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp A_MenuList in BCP\A_MenuList.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp Sys_Creator in BCP\Sys_Creator.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp s_SAM_TotalCost_Primary in BCP\s_SAM_TotalCost_Primary.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp A_creator in BCP\A_creator.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp a_o365ServicesFrendlyNames in BCP\a_o365ServicesFrendlyNames.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp Sys_AgentPISA in BCP\Sys_AgentPISA.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp A_Help in BCP\A_Help.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
bcp Odata_json in BCP\Odata_json.bcp -S %SERVERNAME% -d "ARM_CORE" -U "UserNameGoesHere" -P "PasswordGoesHere" -E -t "|" -c 
